### ISSUE TITLE
cannot run x86_energy_perf_policy

### ISSUE THREAD

**Issue by jasek5** [herecura-archived/powerdown-git#1]
Hi,
I had macbook pro with arch - with powerdon-git lasted about 6hours .
i was forced to reinstall arch linux one day.
I installed powerdown-git and now it lasts only 3,5 hour .
when i run command in terminal it's output is 

[powerdown] cannot run x86_energy_perf_policy powersave

i wasn't making any configuration .

**Comment by BlackIkeEagle** [comment]
I can't really help you anymore since I no longer have a macbook, when I was using a macbook I could only use it properly with linux 4.9, newer versions had all sorts of problems, also mostly related to nouveau

**Comment by BlackIkeEagle** [comment]
I'll also remove this package from my repo since I no longer have any use for it

**Comment by jasek5** [comment]
ok :) thank you
